/**
 * Property-based tests for the mobile-connect plugin.
 *
 * **Validates: Requirements 9.1, 9.2, 9.3, 9.5**
 *
 * Properties tested:
 *   - Property 22: One-time token é invalidado após uso único (Req 9.2, 9.3)
 *   - Property 23: Token de conexão mobile expira em 5 minutos (Req 9.1, 9.3)
 *   - Property 24: Revogação de dispositivo invalida JWT imediatamente (Req 9.5)
 */

import fc from "fast-check";
import jwt from "jsonwebtoken";

// We import the modules under test — reset their mutable state between tests
import {
  generateConnectToken,
  addPendingToken,
  isTokenValid,
  pendingTokens,
  isValidTokenFormat,
} from "../token";
import {
  exchangeToken,
  connectedDevices,
  verifyDeviceJwt,
} from "../exchange";
import { revokeDevice, isRevoked, revokedDevices } from "../revoke";

// ---------------------------------------------------------------------------
// Test setup
// ---------------------------------------------------------------------------

const TEST_JWT_SECRET = "test-secret-for-property-tests-only";

beforeEach(() => {
  // Reset all mutable in-memory state before each test
  pendingTokens.clear();
  connectedDevices.clear();
  revokedDevices.clear();
  process.env["JWT_SECRET"] = TEST_JWT_SECRET;
});

afterAll(() => {
  delete process.env["JWT_SECRET"];
});

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** Valid device name: alphanumeric + hyphens, 1–40 chars */
const deviceNameArb = fc.stringMatching(/^[a-zA-Z0-9-]{1,40}$/);

/** A valid token generated by generateConnectToken() */
const validTokenArb = fc.constant(null).map(() => generateConnectToken());

// ---------------------------------------------------------------------------
// Unit tests — token format and basic behaviour
// ---------------------------------------------------------------------------

describe("generateConnectToken", () => {
  it("always produces BAST-XXXX-XXXX format", () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 50 }), (_n) => {
        const token = generateConnectToken();
        expect(isValidTokenFormat(token)).toBe(true);
      })
    );
  });

  it("produces unique tokens across many calls", () => {
    const tokens = new Set(Array.from({ length: 200 }, () => generateConnectToken()));
    // With 4 bytes of randomness (2^32 possibilities), 200 tokens should all be unique
    expect(tokens.size).toBe(200);
  });
});

// ---------------------------------------------------------------------------
// Property 22: One-time token é invalidado após uso único
// Validates: Requirements 9.2, 9.3
// ---------------------------------------------------------------------------

describe("Property 22: One-time token is invalidated after single use", () => {
  /**
   * **Property 22: One-time token é invalidado após uso único**
   *
   * For any token generated and successfully exchanged, any subsequent
   * attempt to exchange the same token must be rejected — even if the
   * token is still within its 5-minute TTL.
   *
   * **Validates: Requirements 9.2, 9.3**
   */
  it("token cannot be exchanged a second time after successful exchange", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();

        const token = generateConnectToken();
        addPendingToken(token);

        // First exchange must succeed
        const firstJwt = exchangeToken(token, deviceName);
        expect(firstJwt).not.toBeNull();

        // Second exchange with the same token must fail
        const secondJwt = exchangeToken(token, deviceName);
        expect(secondJwt).toBeNull();
      }),
      { numRuns: 100 }
    );
  });

  it("token is removed from pendingTokens immediately after exchange", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();

        const token = generateConnectToken();
        addPendingToken(token);

        expect(pendingTokens.has(token)).toBe(true);

        exchangeToken(token, deviceName);

        expect(pendingTokens.has(token)).toBe(false);
      }),
      { numRuns: 100 }
    );
  });

  it("failed exchange (invalid token) does not consume a valid pending token", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();

        const validToken = generateConnectToken();
        addPendingToken(validToken);

        // Attempt exchange with a different (non-pending) token
        const fakeToken = "BAST-0000-0000";
        const result = exchangeToken(fakeToken, deviceName);
        expect(result).toBeNull();

        // The valid token must still be in pendingTokens
        expect(pendingTokens.has(validToken)).toBe(true);
      }),
      { numRuns: 50 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 23: Token de conexão mobile expira em 5 minutos
// Validates: Requirements 9.1, 9.3
// ---------------------------------------------------------------------------

describe("Property 23: Mobile connect token expires in 5 minutes", () => {
  /**
   * **Property 23: Token de conexão mobile expira em 5 minutos**
   *
   * For any token generated, attempting to use it after 5 minutes must
   * result in rejection, even if the token was never used before.
   *
   * **Validates: Requirements 9.1, 9.3**
   */
  it("token is invalid after TTL has elapsed", () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 10 }), // minutes past TTL
        (minutesPast) => {
          pendingTokens.clear();

          const token = generateConnectToken();
          // Manually insert with an already-expired date
          const expiredDate = new Date(Date.now() - minutesPast * 60 * 1000);
          pendingTokens.set(token, expiredDate);

          expect(isTokenValid(token)).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  it("token is valid immediately after creation", () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 50 }), (_n) => {
        pendingTokens.clear();

        const token = generateConnectToken();
        addPendingToken(token);

        expect(isTokenValid(token)).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  it("token is valid just before TTL boundary (4m59s)", () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 50 }), (_n) => {
        pendingTokens.clear();

        const token = generateConnectToken();
        // Set expiry 1 second in the future (just before 5-min TTL would expire)
        const nearExpiry = new Date(Date.now() + 1000);
        pendingTokens.set(token, nearExpiry);

        expect(isTokenValid(token)).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  it("exchangeToken rejects expired tokens", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();

        const token = generateConnectToken();
        // Insert already-expired
        pendingTokens.set(token, new Date(Date.now() - 1000));

        const result = exchangeToken(token, deviceName);
        expect(result).toBeNull();
      }),
      { numRuns: 100 }
    );
  });

  it("exchangeToken rejects tokens not in pendingTokens", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();

        // Token was never added to pendingTokens
        const token = generateConnectToken();
        const result = exchangeToken(token, deviceName);
        expect(result).toBeNull();
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 24: Revogação de dispositivo invalida JWT imediatamente
// Validates: Requirements 9.5
// ---------------------------------------------------------------------------

describe("Property 24: Device revocation invalidates JWT immediately", () => {
  /**
   * **Property 24: Revogação de dispositivo invalida JWT imediatamente**
   *
   * For any device that has been revoked, any subsequent request using
   * that device's JWT must be rejected — regardless of the JWT's own
   * expiry date.
   *
   * **Validates: Requirements 9.5**
   */
  it("revoked device JWT is rejected by verifyDeviceJwt", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();
        revokedDevices.clear();

        // Issue a valid JWT for the device
        const token = generateConnectToken();
        addPendingToken(token);
        const deviceJwt = exchangeToken(token, deviceName);
        expect(deviceJwt).not.toBeNull();

        // Verify it works before revocation
        const beforeRevoke = verifyDeviceJwt(deviceJwt!, isRevoked);
        expect(beforeRevoke).not.toBeNull();
        expect(beforeRevoke!.device).toBe(deviceName);

        // Revoke the device
        revokeDevice(deviceName);

        // JWT must now be rejected
        const afterRevoke = verifyDeviceJwt(deviceJwt!, isRevoked);
        expect(afterRevoke).toBeNull();
      }),
      { numRuns: 100 }
    );
  });

  it("isRevoked returns true immediately after revokeDevice", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        revokedDevices.clear();

        expect(isRevoked(deviceName)).toBe(false);
        revokeDevice(deviceName);
        expect(isRevoked(deviceName)).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  it("revoking one device does not affect other devices", () => {
    fc.assert(
      fc.property(
        deviceNameArb,
        deviceNameArb,
        (deviceA, deviceB) => {
          // Ensure distinct names
          if (deviceA === deviceB) return;

          pendingTokens.clear();
          connectedDevices.clear();
          revokedDevices.clear();

          // Issue JWTs for both devices
          const tokenA = generateConnectToken();
          addPendingToken(tokenA);
          const jwtA = exchangeToken(tokenA, deviceA);

          const tokenB = generateConnectToken();
          addPendingToken(tokenB);
          const jwtB = exchangeToken(tokenB, deviceB);

          expect(jwtA).not.toBeNull();
          expect(jwtB).not.toBeNull();

          // Revoke only device A
          revokeDevice(deviceA);

          // Device A's JWT must be rejected
          expect(verifyDeviceJwt(jwtA!, isRevoked)).toBeNull();

          // Device B's JWT must still be valid
          const verifiedB = verifyDeviceJwt(jwtB!, isRevoked);
          expect(verifiedB).not.toBeNull();
          expect(verifiedB!.device).toBe(deviceB);
        }
      ),
      { numRuns: 100 }
    );
  });

  it("device is removed from connectedDevices after revocation", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();
        revokedDevices.clear();

        const token = generateConnectToken();
        addPendingToken(token);
        exchangeToken(token, deviceName);

        expect(connectedDevices.has(deviceName)).toBe(true);

        revokeDevice(deviceName);

        expect(connectedDevices.has(deviceName)).toBe(false);
      }),
      { numRuns: 100 }
    );
  });

  it("JWT signed with correct secret is verifiable before revocation", () => {
    fc.assert(
      fc.property(deviceNameArb, (deviceName) => {
        pendingTokens.clear();
        connectedDevices.clear();
        revokedDevices.clear();

        const token = generateConnectToken();
        addPendingToken(token);
        const deviceJwt = exchangeToken(token, deviceName);
        expect(deviceJwt).not.toBeNull();

        // Manually verify the JWT structure
        const decoded = jwt.verify(deviceJwt!, TEST_JWT_SECRET) as {
          device: string;
          iat: number;
          exp: number;
        };
        expect(decoded.device).toBe(deviceName);
        // exp should be ~90 days from now
        const expectedExp = Math.floor(Date.now() / 1000) + 90 * 24 * 60 * 60;
        expect(Math.abs(decoded.exp - expectedExp)).toBeLessThan(5); // within 5 seconds
      }),
      { numRuns: 50 }
    );
  });
});
